application: vds229-ost
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /rss/.*
  script: rss.application

- url: /manage
  script: manage.application

- url: /manage/.*
  script: manage.application

- url: /upload
  script: image.application

- url: /img/.*
  script: image.application

# home page, showcases [random?] posts or user's posts
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
